### ISSUE TITLE
Update vlucas/phpdotenv 

### ISSUE THREAD

**Issue by gallexme** [codemix/yii2-configloader#4]
you are using a way to old version
v2.5.1 is already out

**Comment by mikehaertl** [comment]
Well, it still works. Any specific feature you're missing? 

When I find time I'll have a look and try to upgrade to a newer version.

**Comment by gallexme** [comment]
its not about features, its about security/version incompabilities
u use a 4 year old version of a package which has been regularly updated for the last 4 years and is now already in version 2.5, ther might security issues/bugs in that version which have long been fixed, or have been updated for compability with newer php versions

also anyone who wants to use ur package or has ur package in the dependencies is forced to use the old phpdotenv version, which might break other packages the user uses as they may depend on phpdotenv too 
there are currently  2116 composer packages depending on phpdotenv

**Comment by mikehaertl** [comment]
@gallexme I've updated to 2.5.x now. They've changed their interface quite a bit but I tried to keep our library consistent. Feel free to comment on the PR or test the code.

**Comment by mikehaertl** [comment]
Released 0.10.0. Please let me know of any issues.
